package jp.hidemaru.burnedcaptionreader.ocr;
import org.junit.Test;import static org.junit.Assert.*;import java.util.*;
public class PpOcrDetectionTest {
 @Test public void channelOrderShapeAndNormalization(){PpOcrDetectionInput i=PpOcrDetectionInput.fromArgb(new int[]{0xffff0000},1,1);assertEquals(640,i.width);assertEquals(640,i.height);int n=i.width*i.height;assertEquals(-.485f/.229f,i.values[0],1e-6);assertEquals(-.456f/.224f,i.values[n],1e-6);assertEquals((1-.406f)/.225f,i.values[2*n],1e-6);}
 @Test public void preservesRatioBeforeDivisorRounding(){PpOcrDetectionInput i=PpOcrDetectionInput.fromArgb(new int[850*479],850,479);assertEquals(640,i.width);assertEquals(384,i.height);}
 @Test public void rejectsMalformedInput(){try{PpOcrDetectionInput.fromArgb(new int[1],2,1);fail();}catch(IllegalArgumentException expected){}}
 @Test public void expandsSeparateComponentsAndRejectsWeakBoxes(){float[]m=new float[100*80];for(int y=10;y<20;y++)for(int x=10;x<60;x++)m[y*100+x]=.9f;for(int y=45;y<55;y++)for(int x=10;x<60;x++)m[y*100+x]=.5f;List<PpOcrDbPostProcessor.Box>b=PpOcrDbPostProcessor.decode(m,100,80);assertEquals(1,b.size());assertTrue(b.get(0).left<.1);assertTrue(b.get(0).right>.59);assertTrue(b.get(0).top<.125);assertEquals(.9,b.get(0).score,1e-6);assertTrue(Math.abs(b.get(0).angle)<1);}
 @Test public void rejectNonfiniteAndOversizedMaps(){for(float v:new float[]{Float.NaN,Float.POSITIVE_INFINITY,-1}){try{PpOcrDbPostProcessor.decode(new float[]{v},1,1);fail();}catch(IllegalArgumentException expected){}}try{PpOcrDbPostProcessor.decode(new float[1],2,2);fail();}catch(IllegalArgumentException expected){}}
 @Test public void alreadyDetectedRowsAndSmallLabelsAreNotAdded(){PpOcrDbPostProcessor.Box b=new PpOcrDbPostProcessor.Box(new float[]{.2f,.6f,.8f,.6f,.8f,.7f,.2f,.7f},.9);assertTrue(PpOcrCaptionRescue.missingCaptionShape(b,Collections.emptyList(),850,479));assertFalse(PpOcrCaptionRescue.missingCaptionShape(b,List.of(new OcrLine(0,"既存字幕",55,.3f,.61f,.7f,.69f)),850,479));assertFalse(PpOcrCaptionRescue.acceptsReading("会社",.99));assertFalse(PpOcrCaptionRescue.acceptsReading("読み取り信頼度不足",.5));assertTrue(PpOcrCaptionRescue.acceptsReading("動画の字幕です",.95));}
 @Test public void plainWhitePaperCannotTeachCaptionRescue(){int[]p=new int[850*479];Arrays.fill(p,0xffffffff);PpOcrDbPostProcessor.Box b=new PpOcrDbPostProcessor.Box(new float[]{.2f,.6f,.8f,.6f,.8f,.7f,.2f,.7f},.9);assertEquals(0,PpOcrCaptionRescue.outlinedGlyphHeight(p,850,479,b),0);}
 @Test public void appendKeepsOriginalMetadataAndProbabilitySeparate(){OcrLine l=new OcrLine(4,"既存の会話",85,.1f,.1f,.8f,.2f);OcrResult original=new OcrResult(l.getText(),85,List.of(l));assertSame(original,PpOcrCaptionRescue.append(original,Collections.emptyList()));OcrLine rescue=new OcrLine(5,"追加の字幕です",55,.1f,.6f,.8f,.7f,Collections.emptyList(),.06f,.95);OcrResult out=PpOcrCaptionRescue.append(original,List.of(rescue));assertSame(l,out.getLines().get(0));assertEquals(85,out.getLines().get(0).getConfidence(),0);assertEquals(55,out.getLines().get(1).getConfidence(),0);assertEquals(.95,out.getLines().get(1).getModelProbability(),0);}
 @Test public void repairRejectsAmbiguousAndMultilineMatches(){PpOcrDbPostProcessor.Box b=new PpOcrDbPostProcessor.Box(new float[]{.1f,.6f,.9f,.6f,.9f,.7f,.1f,.7f},.9);assertEquals(-1,PpOcrCaptionRescue.matchingRow(b,List.of()));OcrLine a=new OcrLine(3,"動画の字幕",40,.1f,.6f,.9f,.7f);assertEquals(0,PpOcrCaptionRescue.matchingRow(b,List.of(a)));assertEquals(-2,PpOcrCaptionRescue.matchingRow(b,List.of(a,a)));assertEquals(-2,PpOcrCaptionRescue.matchingRow(b,List.of(new OcrLine(1,"二行の文章",55,.1f,.5f,.9f,.8f))));}
 @Test public void repairKeepsBlockAndDoesNotSubstituteModelProbabilityForConfidence(){PpOcrDbPostProcessor.Box b=new PpOcrDbPostProcessor.Box(new float[]{.1f,.6f,.9f,.6f,.9f,.7f,.1f,.7f},.9);OcrLine a=new OcrLine(7,"字幕",40,.1f,.6f,.9f,.7f);assertFalse(PpOcrCaptionRescue.acceptsRepair(a,"動画の字幕です",.95));assertTrue(PpOcrCaptionRescue.acceptsRepair(a,"動画の字幕です",.99));OcrLine fixed=PpOcrCaptionRescue.repaired(a,b,"動画の字幕です",.06f,.99);assertEquals(7,fixed.getBlockIndex());assertEquals(55,fixed.getConfidence(),0);assertEquals(.99,fixed.getModelProbability(),0);}
}
